version: '3.3'

services:
  weeboo:
    container_name: 'weeboo-bot'
    restart: always
    build: .
    env_file: stack.env
    command: python -u /bots/weeboo/bot.py
  listy:
    container_name: 'listy-bot'
    restart: always
    build: .
    env_file: stack.env
    command: python -u /bots/listy/bot.py

